pub const TEST_CASES: [(&str, &str, Result<bool, &str>); 89] = [
    (
        "(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)9",
        "abcdefghijkl9",
        Ok(true),
    ),
    ("a.b", "acb", Ok(true)),
    (")", "", Err("")),
    ("", "", Ok(true)),
    ("abc", "abc", Ok(true)),
    ("abc", "xbc", Ok(false)),
    ("abc", "axc", Ok(false)),
    ("abc", "abx", Ok(false)),
    ("abc", "xabcy", Ok(true)),
    ("abc", "ababc", Ok(true)),
    ("ab*c", "abc", Ok(true)),
    ("ab*bc", "abc", Ok(true)),
    ("ab*bc", "abbc", Ok(true)),
    ("ab*bc", "abbbbc", Ok(true)),
    ("ab+bc", "abbc", Ok(true)),
    ("ab+bc", "abc", Ok(false)),
    ("ab+bc", "abq", Ok(false)),
    ("ab+bc", "abbbbc", Ok(true)),
    ("ab?bc", "abbc", Ok(true)),
    ("ab?bc", "abc", Ok(true)),
    ("ab?bc", "abbbbc", Ok(false)),
    ("ab?c", "abc", Ok(true)),
    ("a.c", "abc", Ok(true)),
    ("a.c", "axc", Ok(true)),
    ("a.*c", "axyzc", Ok(true)),
    ("a.*c", "axyzd", Ok(false)),
    ("a[bc]d", "abc", Ok(false)),
    ("a[bc]d", "abd", Ok(true)),
    ("a[]b", "-", Err("")),
    ("a[", "-", Err("")),
    ("a\\", "-", Err("")),
    ("abc)", "-", Err("")),
    ("(abc", "-", Err("")),
    ("a]", "a]", Ok(true)),
    ("a[]]b", "a]b", Ok(true)),
    ("a[\\]]b", "a]b", Ok(true)),
    ("ab|cd", "abc", Ok(true)),
    ("ab|cd", "abcd", Ok(true)),
    ("()ef", "def", Ok(true)),
    ("a\\(b", "a(b", Ok(true)),
    ("a\\(*b", "ab", Ok(true)),
    ("a\\(*b", "a((b", Ok(true)),
    ("a\\\\b", "a\\b", Ok(true)),
    ("((a))", "abc", Ok(true)),
    ("(a)b(c)", "abc", Ok(true)),
    ("a+b+c", "aabbabc", Ok(true)),
    ("(a+|b)*", "ab", Ok(true)),
    ("(a+|b)+", "ab", Ok(true)),
    ("(a+|b)?", "ab", Ok(true)),
    (")(", "-", Err("")),
    ("abc", "", Ok(false)),
    ("a*", "", Ok(true)),
    ("a|b|c|d|e", "e", Ok(true)),
    ("(a|b|c|d|e)f", "ef", Ok(true)),
    ("abcd*efg", "abcdefg", Ok(true)),
    ("ab*", "xabyabbbz", Ok(true)),
    ("ab*", "xayabbbz", Ok(true)),
    ("(ab|cd)e", "abcde", Ok(true)),
    ("[abhgefdc]ij", "hij", Ok(true)),
    ("(abc|)ef", "abcdef", Ok(true)),
    ("(a|b)c*d", "abcd", Ok(true)),
    ("(ab|ab*)bc", "abc", Ok(true)),
    ("a([bc]*)c*", "abc", Ok(true)),
    ("a([bc]*)(c*d)", "abcd", Ok(true)),
    ("a([bc]+)(c*d)", "abcd", Ok(true)),
    ("a([bc]*)(c+d)", "abcd", Ok(true)),
    ("a[bcd]*dcdcde", "adcdcde", Ok(true)),
    ("a[bcd]+dcdcde", "adcdcde", Ok(false)),
    ("(ab|a)b*c", "abc", Ok(true)),
    ("((a)(b)c)(d)", "abcd", Ok(true)),
    ("(((((((((a)))))))))", "a", Ok(true)),
    ("multiple words of text", "uh-uh", Ok(false)),
    ("multiple words", "multiple words, yeah", Ok(true)),
    ("(.*)c(.*)", "abcde", Ok(true)),
    ("\\((.*), (.*)\\)", "(a, b)", Ok(true)),
    ("[k]", "ab", Ok(false)),
    ("(a)(b)c|ab", "ab", Ok(true)),
    ("(a)+x", "aaax", Ok(true)),
    ("([ac])+x", "aacx", Ok(true)),
    ("([abc]*)x", "abcx", Ok(true)),
    ("([abc]*)x", "abc", Ok(false)),
    ("([xyz]*)x", "abcx", Ok(true)),
    ("(a)+b|aac", "aac", Ok(true)),
    ("*a", "-", Err("")),
    ("(*)b", "-", Err("")),
    ("a**", "-", Err("")),
    ("([abc])*d", "abbbcd", Ok(true)),
    ("([abc])*bcd", "abcd", Ok(true)),
    ("((((((((((a))))))))))", "a", Ok(true)),
];
